disableStartupPopups: true

git:
  diffRenderers:
    - command: delta --paging=never

gui:
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 2
  filterMode: fuzzy
  nerdFontsVersion: "3"
  scrollHeight: 8
  scrollPastBottom: false
  showCommandLog: false
  showRandomTip: false
  sidePanelWidth: .2
