[mgr]
show_hidden = true

[opener]
edit = [
    { run = 'nvim "$@"', block = true, for = "unix" },
    { run = 'nvim %*', block = true, for = "windows" },
]
extract = [
    { run = 'ouch d -y "$@"', desc = "Extract here with ouch", for = "unix" },
    { run = 'ouch d -y %*', desc = "Extract here with ouch", for = "windows" },
]

[plugin]
prepend_preloaders = [
    # Replace magick, image, video with mediainfo
    { mime = "{audio,video,image}/*", run = "mediainfo" },
    { mime = "application/subrip", run = "mediainfo" },
]
prepend_previewers = [
    # Replace magick, image, video with mediainfo
    # https://mediaarea.net/en/MediaInfo/Support/Formats
    { mime = "{audio,video,image}/*", run = "mediainfo" },
    { mime = "application/subrip", run = "mediainfo" },
    # Archive previewer
    { mime = "application/*zip", run = "ouch" },
    { mime = "application/x-tar", run = "ouch" },
    { mime = "application/x-bzip2", run = "ouch" },
    { mime = "application/x-7z-compressed", run = "ouch" },
    { mime = "application/x-rar", run = "ouch" },
    { mime = "application/x-xz", run = "ouch" },
    { mime = "application/xz", run = "ouch" },
]
